promoter_upstream_1kb:
  path: 'some_path'
  number_of_chunk: 10
  prepare_input_script: 'script name in scripts/'
name: 'promoter_upstream_1kb'
deep_variant:
  model:
    model_name: 'model path'
    name: 'model_name'
  label:
    group_name: 'label'
    entry:
      E081: 1
      E129: 3
      Noonan: 4
  path_to_annotation: 'some path'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19/hg19.fa'
