promoter_upstream_1kb:
  path: '/project2/xinhe/yanyul/repo/genomewide_annotation/data/refseq_id_promoter_1kb_upstream_pair_table.txt'
  number_of_chunk: 10
  prepare_input_script: 'prepare_deep_variant.py'
name: 'promoter_upstream_1kb'
deep_variant:
  model:
    model_name: 'model path'
    name: 'model_name'
  label:
    group_name: 'label'
    entry:
      E081: 1
      E129: 3
      Noonan: 4
  path_to_annotation: 'some path'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.chrom.sizes'
