promoter_upstream_downstream_1kb:
  path: '/project2/xinhe/yanyul/repo/genomewide_annotation/data/refseq_id_promoter_1kb_upstream_downstream_pair_table.txt'
  number_of_chunk: 100
  prepare_input_script: 'prepare_deep_variant.py'
name: 'promoter_upstream_downstream_1kb'
deep_variant:
  model_tag: 'paperNSC'
  paperNSC:
    path: '/project2/xinhe/yanyul/repo/deep_variant/train_deepsea/model/'
    name: 'DeepSEA-paperNSC_logistic.best_copy'
  label:
    group_name: 'label'
    entry:
      d27: 1
      d41-1: 2
      d41-2: 3
  path_to_annotation: '/project2/xinhe/yanyul/scratch/DeepVariantPrediction/'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
footprint_annotation:
  model_tag: 'paperNSC'
  end_include: '0'
  paperNSC:
    d27: '../strategy2/combine_result/output/paperNSC_d27.final.bed.gz.temp'
    d41-1: '../strategy2/combine_result/output/paperNeuron_d41_1.final.bed.gz.temp'
    d41-2: '../strategy2/combine_result/output/paperNeuron_d41_2.final.bed.gz.temp'
  path_to_annotation: '/project2/xinhe/yanyul/scratch/footprint_annotation/strategy1/' # combine_result/output/'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
footprint_annotation-strategy2:  # note that this module based completely on the output of strategy2
  model_tag: 'paperNSC'
  end_include: '0'
  motif_folder: '../data/motif_in_meme/recalMotifs/'
  motif_str: '../model/recalMotifs/\{motif\}__\{data_name\}__window.200.rds'
  paperNSC:  # note that the data name should match the one in strategy2 in order to find the trained model correctly
    paperNSC_d27: '../combine_result/output/paperNSC_d27.final.bed.gz.temp'
    paperNeuron_d41_1: '../combine_result/output/paperNeuron_d41_1.final.bed.gz.temp'
    paperNeuron_d41_2: '../combine_result/output/paperNeuron_d41_2.final.bed.gz.temp'
  path_to_annotation: '/project2/xinhe/yanyul/scratch/footprint_annotation/strategy2/annotation/' # combine_result/output/'
  methods:
    nothing:
      calculator: 'nothing'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.chrom.sizes'
snakemake_dir: '/project2/xinhe/yanyul/scratch/genomewide_annotation/'
