promoter_upstream_1kb:
  path: '/project2/xinhe/yanyul/repo/genomewide_annotation/data/refseq_id_promoter_1kb_upstream_pair_table.txt'
  number_of_chunk: 100
  prepare_input_script: 'prepare_deep_variant.py'
name: 'promoter_upstream_1kb'
deep_variant:
  model_tag: 'deepsea-stage1'
  deepsea-stage1:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/'
    name: 'keras_deepsea_with_040417_2_42_head_copy'
  label:
    group_name: 'label'
    entry:
      E081: 1
      E129: 3
      Noonan: 4
  path_to_annotation: '/project2/xinhe/yanyul/deep_variant/nick/DeepVariantPrediction'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
      # filter: 'hard_log_thresholding'
      # param: 2  # Hard threshold
footprint_annotation:
  model_tag: 'fetal-brain-roadmap'
  fetal-brain-roadmap:
    SRX026914: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX026914.bed.gz'
    SRX027076: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027076.bed.gz'
    SRX027083: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027083.bed.gz'
    SRX027085: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027085.bed.gz'
    SRX027086: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027086.bed.gz'
    SRX027089: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027089.bed.gz'
    SRX027091: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX027091.bed.gz'
    SRX040380: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX040380.bed.gz'
    SRX040395: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX040395.bed.gz'
    SRX062364: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX062364.bed.gz'
    SRX121276: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX121276.bed.gz'
    SRX121277: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX121277.bed.gz'
    SRX121278: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX121278.bed.gz'
    SRX201815: '../footprintRegions/EpiUwRmapDNaseFetal.Brain.SRX201815.bed.gz'
  path_to_annotation: '/project2/xinhe/yanyul/repo/footprint_annotation/strategy1'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
      # filter: 'hard_log_thresholding'
      # param: 2  # Hard threshold
    # footprint_snp:
    #   calculator: 'nothing'
    #   # filter: 'footprint_snp'
    #   # param: 'None'
    # binding_variant:
    #   calculator: 'abs_change'
    #   # filter: 'binding_variant'
    #   # param: '0.9,20'  # Prior binding prob >= 0.9 and log fold change >= log(20)
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.chrom.sizes'
snakemake_dir: '/project2/xinhe/yanyul/repo/genomewide_annotation/'
