promoter_upstream_downstream_1kb_NoonanRoadmap:
  path: '/project2/xinhe/yanyul/repo/genomewide_annotation/preprocess/intersect/promoter_upstream_downstream_1kb__NoonanRoadmap.bed'
  number_of_chunk: 55
  prepare_input_script: 'prepare_deep_variant.py'
name: 'promoter_upstream_downstream_1kb_NoonanRoadmap'
deep_variant:
  model_tag: 'deepsea-noonan-roadmap'
  deepsea-noonan-roadmap:
    path: '/project2/xinhe/yanyul/repo/deep_variant/train_deepsea/model/'
    name: 'DeepSEA-NoonanRoadmap_logistic.best_copy'
  label:
    group_name: 'label'
    entry:
      NoonanRoadmap: 1
  path_to_annotation: '/scratch/midway2/xinhe/DeepVariantPrediction/'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
footprint_annotation:
  model_tag: 'No_model'
  No_model:
    No_label: ''
  path_to_annotation: ''
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.chrom.sizes'
snakemake_dir: '/project2/xinhe/yanyul/repo/genomewide_annotation/'

