promoter_upstream_downstream_1kb:
  path: '/project2/xinhe/yanyul/repo/genomewide_annotation/data/refseq_id_promoter_1kb_upstream_downstream_pair_table.txt'
  number_of_chunk: 100
  prepare_input_script: 'prepare_deep_variant.py'
name: 'promoter_upstream_downstream_1kb'
deep_variant:
  number_of_chunk: 25
  model_tag: 'deepsea-stage1'
  deepsea-stage1:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/'
    name: 'keras_deepsea_with_040417_2_42_head_copy'
  label:
    group_name: 'label'
    entry:
      E081: 
        idx: 1
        region: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E081-DNase.macs2.narrowPeak.sorted'
  path_to_annotation: '/project2/xinhe/yanyul/deep_variant/nick/DeepVariantPrediction'
  methods:
    log_odds_ratio:
      calculator: 'log_odds_ratio'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.fa'
  size: '/project2/xinhe/yanyul/databases/hg19_complete/hg19.chrom.sizes'
snakemake_dir: '/project2/xinhe/yanyul/repo/genomewide_annotation/'
